### ISSUE TITLE
Question regarding train.csv dataset

### ISSUE THREAD

**Issue by bdowdell** [pddasig/Machine-Learning-Competition-2020#2]
After spending some time inspecting the train.csv data set, I am curious if it is intentional that the DTC & DTS (target response variables) have gaps?  I understand the goal is to predict these curves when they are missing, but it seems that having them missing in the training dataset is suboptimal?

Here is the data contained in train.csv.  Other than replacing the -999 values with NaN's, no editing has been performed:
![image](https://user-images.githubusercontent.com/42157926/76692366-83d6c380-6623-11ea-96d6-c71aa891190a.png)

Referring to the example notebook, it appears that there are no missing values in either the DTC or DTS:
![image](https://user-images.githubusercontent.com/42157926/76692390-d9ab6b80-6623-11ea-9a81-e8a47fcc23c7.png)

Additionally, the PE curve seems to effectively end after approximately index 20,000.  When the rest of the shallower data is removed due to the missing segments in DTC & DTS, it seems to reduce this down to using CAL, GR, CNC, HRD, HRM, & ZDEN.

My primary concern is if this is intentional, then it seems to remove a substantial amount of samples for training a model given this is based on a single well.  Could you please comment on this?

Thanks!

**Comment by pddasig** [comment]
Hello Ben,

Actually this training dataset is a true logging dataset combined from three wells. In some wells, the logs may not be complete, and we intentionally remove the depth information, that's why the DTC or DTS have the gaps.
Also, the purpose of this competition is to test if a data-driven method can help the petrophysicist generate the pseudo curves. Therefore, all the available data is left to the participants, after the competition we can see what the best model looks like. 

Best,
Yanxiang

**Comment by bdowdell** [comment]
Ok, thanks for the information.
